substitutions:
  m5stack_atoms3r:
    id:
      i2c: m5stack_atoms3r_i2c
      i2c_grove: m5stack_atoms3r_i2c_grove
      button: m5stack_atoms3r_button
      lp5562: m5stack_atoms3r_lp5562
      output: m5stack_atoms3r_output
      light: m5stack_atoms3r_light
      spi: m5stack_atoms3r_spi
      display: m5stack_atoms3r_display
    display:
      width: 128
      height: 128
      size: "128x128"
    gpio:
      button: GPIO41
      i2c:
        scl: GPIO0
        sda: GPIO45
      grove:
        _0: GPIO1
        _1: GPIO2
      spi:
        clk: GPIO15
        mosi: GPIO21
      ir: GPIO47
      display:
        dc: GPIO42
        reset: GPIO48
        cs: GPIO14
  m5stack_atom_bus:
    _0:
      _0: GPIO39
      _1: GPIO38
    _1:
      _1: GPIO5
      _2: GPIO6
      _3: GPIO7
      _4: GPIO8

external_components: 
  - source: github://m5stack/esphome-yaml/components@main
    components: [lp5562]

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240Mhz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

binary_sensor:
  - id: ${m5stack_atoms3r.id.button}
    platform: gpio
    pin:
      number: ${m5stack_atoms3r.gpio.button}
      mode: INPUT_PULLUP
      inverted: true
    internal: true

i2c:
  - id: ${m5stack_atoms3r.id.i2c}
    scl:
      number: ${m5stack_atoms3r.gpio.i2c.scl}
      ignore_strapping_warning: true
    sda:
      number: ${m5stack_atoms3r.gpio.i2c.sda}
      ignore_strapping_warning: true
    scan: true
  - id: ${m5stack_atoms3r.id.i2c_grove}
    scl: ${m5stack_atoms3r.gpio.grove._0}
    sda: ${m5stack_atoms3r.gpio.grove._1}
    scan: true

lp5562: 
  id: ${m5stack_atoms3r.id.lp5562}
  i2c_id: ${m5stack_atoms3r.id.i2c}
  use_internal_clk: true
  high_pwm_freq: true
  logarithmic_dimming: true
  white_current: 17.5

output:
  - id: ${m5stack_atoms3r.id.output}
    platform: lp5562
    lp5562_id: ${m5stack_atoms3r.id.lp5562}
    channel: white

light:
  - id: ${m5stack_atoms3r.id.light}
    platform: monochromatic
    output: ${m5stack_atoms3r.id.output}

spi:
  id: ${m5stack_atoms3r.id.spi}
  interface: spi2
  clk_pin: ${m5stack_atoms3r.gpio.spi.clk}
  mosi_pin: ${m5stack_atoms3r.gpio.spi.mosi}

display:
  - id: ${m5stack_atoms3r.id.display}
    platform: mipi_spi
    model: ST7789V
    dc_pin: ${m5stack_atoms3r.gpio.display.dc}
    reset_pin: ${m5stack_atoms3r.gpio.display.reset}
    cs_pin: ${m5stack_atoms3r.gpio.display.cs}
    data_rate: 40MHz
    dimensions:
      width: ${m5stack_atoms3r.display.width}
      height: ${m5stack_atoms3r.display.height}
      offset_height: 1
      offset_width: 2
    invert_colors: true