packages:
  - !include
    file: m5stack_atoms3r.yaml
    vars:
      spi_interface: spi2
      spi: spi_
      lp5562: lp5562_
      output: output_
      i2c: i2c_
      i2c_grove: i2c_grove_
      light: light_
      display: display_
      button: button_
      motion: motion_

  - !include
    file: m5stack_atomic_poe_base.yaml
    vars:
      ethernet_interface: spi3
      ethernet_clk_pin: ${m5stack_atoms3r.atom_bus[1][1]}
      ethernet_cs_pin: ${m5stack_atoms3r.atom_bus[1][2]}
      ethernet_miso_pin: ${m5stack_atoms3r.atom_bus[1][3]}
      ethernet_mosi_pin: ${m5stack_atoms3r.atom_bus[1][4]}

  - !include
    file: apms.yaml
    vars:
      i2c: i2c_grove_
      light: light_
      display: display_
      button: button_
      motion: motion_
      display_size: ${m5stack_atoms3r.display.size}
